version: '3.8'

services:
  server:
    build: ./backend
    ports:
      - "4000:80"
    depends_on:
      - mysql
    networks:
      - backend
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    networks:
      - backend
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

networks:
  backend: